### PR TITLE
Add a SECURITY.md

### PR DESCRIPTION
**Pull request by ReinderVosDeWael**
This PR adds a security policy which informs users on how to inform us of security vulnerabilities in our applications. For an example usage, see the side bar of https://github.com/cmi-dair/cross-species-mapper/ . 

Instructions have been added to the README.md to either modify SECURITY.md, or delete it if it's not relevant.

### CODE REVIEW

**Review by nx10 — APPROVED** [review]

**Comment by clane9** [comment]
Personally I'm a bit opposed to worrying about security. I know this is not the "right way", but I feel like it's often not a necessity for the sort of stuff we're building (cf [pybids](https://github.com/bids-standard/pybids) and [nilearn](https://github.com/nilearn/nilearn) do not have a SECURITY.md). And maintaining a responsible security policy seems hard. My 2c would be to not put this in the template, but add it to projects that require it.

**Comment by ReinderVosDeWael** [comment]
@gkiar tie breaker on these opposing reviews? :)

**Comment by ReinderVosDeWael** [comment]
It'd only not be a necessity if there's no vulnerabilities, which means there's no work to do anyway :). Security should always be a concern; it takes but a single significant data leak to drag CMI's reputation into the gutter.

**Comment by gkiar** [comment]
Afaict, the policy is just:
- we care about security
- tell us privately so we can address

I see no harm in including that in templates? As @clane9 rightly points out: most of the time this is irrelevant for what we do, and, as @ReinderVosDeWael says, when it is relevant, it's important and we want to cover our bases.

**Review by gkiar — APPROVED** [review]

**Pull request merged**
