### PR TITLE
Add stability badge to readme fix #30

### LINKED ISSUE #30: Add an API stability badge to the README
There should be a clear way of communicating to potential users what the current state of development is and the stability of the API.

- [ ] Add a badge for stability.
- [ ] Add an explanation in the README of the different states this badge can have.
  - [ ] C.f. https://nodejs.org/api/documentation.html#documentation_stability_index and https://github.com/badges/stability-badges for examples.

### PR DESCRIPTION
**Pull request by nx10**
- Resolves #30

### CODE REVIEW

**Comment by ReinderVosDeWael** [comment]
Should we refer to the more node website rather than this repo? The node one has documentation on what each label means , and we can create any custom badge; we don't have to rely on that repo e.g.

https://img.shields.io/badge/sup_florian-im_very_cool-pink.svg

**Comment by nx10** [comment]
Either way for me, I just found that specific repo I linked had good defaults (colors and text) and 1 sentence description. Maybe we can link both

**Comment by nx10** [comment]
Yeah agreed, I'd still like to link the repo just to be able to quickly copy them but the node website should be the definitive guide

**Comment by ReinderVosDeWael** [comment]
Ah gotchya, yeah sure, if you add that to the README it's a +1 from me.

**Review by ReinderVosDeWael — APPROVED** [review]

**Pull request merged**
